#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
    ['proactive-jupyter-kernel']

package_data = \
    {'': ['*']}

install_requires = \
    ['pexpect>=4.0', 'proactive', 'jupyter_client', 'IPython', 'traitlets', 'ipykernel', 'notebook']

setup(name='proactive-jupyter-kernel',
      version='0.1',
      description='A proactive kernel for Jupyter',
      author='ActiveEon',
      author_email='www.activeeon.com',
      url='https://github.com/ow2-proactive/proactive-jupyter-kernel',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      )
